dependencies {
    // jts
    implementation(libs.jts)
    additionalRuntimeClasspath(libs.jts)
    jarJar(libs.jts)

    // Anvil Lib
    implementation(libs.anvillib)
    // interfaceInjectionData(libs.anvillib)

    // AnvilCraft
    implementation(libs.anvilcraft) { transitive = false }
    interfaceInjectionData(libs.anvilcraft) { transitive = false }

    // Curios API
    implementation(libs.curios)
}
