dependencies {
    // Registrate
    api(libs.registrate)

    // jts
    implementation(libs.jts)
    jarJar(libs.jts)

    // Cloth Config
    implementation(libs.clothConfig)

    // AnvilCraft
    implementation(libs.anvilCraft) { transitive = false }

    // Curios API
    implementation(libs.curios)
}
